# Action to request to the controller. It is application-dependent,
# but some defaults are available.

string LIST_ACTIONS     = "list_actions"
string ACTION_HOME      = "home"
string ACTION_RELEASE   = "release"

string action

# ID of the object (max 255)
int16[] object

---

# True false if action was successful or not
bool   success

# Additional information that occasionally is added to the response
# message. For now, it is used to provide more information how and
# why an action failed. There may be multiple reasons, but some
# defaults are listed below.

string NO_OBJ   = "No object detected"
string ACT_FAIL = "Action failed from user input"

string response
