string action
# id of object (max 255)
int16[] object
---

# True false if action was successful or not
bool   success

# Additional information that occasionally is added to the response
# message. For now, it is used to provide more information how and
# why an action failed. There may be multiple reasons, but some
# defaults are listed below

string NO_OBJ   = "No object detected"
string ACT_FAIL = "Action failed from user input"

string response
